export const scheduleData = {
    totalEvents: 11,
    categories: ['All', 'Networking', 'Education', 'Planet', 'Art', 'Technology', 'Food', 'Finance', 'Challenge'],
    days: ['SAT'],
    schedule: [
        {
            id: 1,
            title: "Breakfast and Networking",
            date: "July 18",
            time: "8:30 AM",
            type: "NETWORKING",
            description: "Start the day with breakfast and connect with fellow attendees, speakers, and partners.",
            day: 'SAT',
            category: 'Networking',
        },
        {
            id: 2,
            title: "Opening Remark",
            date: "July 18",
            time: "9:00 AM - 9:30 AM",
            type: "KEYNOTE",
            speaker: "Xiaoran Cai",
            description: "The AI and Sustainability Global Summit brings together leaders from academia, industry, government, and entrepreneurship to explore how artificial intelligence can be leveraged to accelerate sustainable development. The summit focuses on three core themes: AI for Climate and Environmental Solutions, AI in Education for Sustainable Futures, and Ethical and Inclusive AI for People and Planet.",
            day: 'SAT',
            category: 'Opening',
        },
        {
            id: 3,
            title: "AI and Education",
            date: "July 18",
            time: "9:30 AM - 10:30 AM",
            type: "PANEL",
            description: "This session explores how education can harness the power of AI to cultivate a new wave of entrepreneurs committed to sustainability. As institutions rethink how they prepare students for the green economy, AI offers tools to personalize learning, simulate real-world challenges, and support venture creation.",
            day: 'SAT',
            category: 'Education',
        },
        {
            id: 4,
            title: "AI and the Planet",
            date: "July 18",
            time: "10:30 AM - 11:30 AM",
            type: "PANEL",
            speaker: "Matt James",
            description: "Yes, we are in crisis. Species extinction is accelerating, ecosystems are under pressure, and the planet is approaching critical tipping points. The urgency is real. This panel emphasized that while the challenges are immense, technology can play a powerful role in addressing them. From tracking endangered species DNA to optimizing conservation efforts and network, AI gives us tools to respond faster, smarter, and at scale.",
            day: 'SAT',
            category: 'Planet',
        },
        {
            id: 5,
            title: "AI and Art",
            date: "July 18",
            time: "11:30 AM - 12:30 PM",
            type: "PANEL",
            speaker: "Matthew Collado",
            description: "AI is making every artistic dream feel possible and important. By keeping humans at the center, it brings more joy and meaning to the creative process. Accessibility doesn't mean compromise, but rather, better quality and new possibilities for everyone.",
            day: 'SAT',
            category: 'Art',
        },
        {
            id: 6,
            title: "Lunch and Networking",
            date: "July 18",
            time: "12:30 PM - 13:30 PM",
            type: "NETWORKING",
            description: "Enjoy lunch while networking with peers and discussing the morning sessions.",
            day: 'SAT',
            category: 'Networking',
        },
        {
            id: 7,
            title: "AI and Technology",
            date: "July 18",
            time: "13:30 PM - 14:30 PM",
            type: "PANEL",
            speaker: "Emily Fontaine",
            description: "Artificial intelligence is transforming the traditional cost-performance trade-off in business and technology. Rather than sacrificing quality or speed for savings, leading experts will share how AI enables organizations to simultaneously reduce operational costs and enhance capabilities — from automating complex tasks to optimizing decision-making and driving innovation.",
            day: 'SAT',
            category: 'Technology',
        },
        {
            id: 8,
            title: "AI and Finance, Compliance and Investment",
            date: "July 18",
            time: "14:30 PM - 15:30 PM",
            type: "PANEL",
            speaker: "Veeral Shah",
            description: "AI is reshaping finance by enhancing compliance, improving investment strategies, and driving ethical, data-driven decision-making across the sector.",
            day: 'SAT',
            category: 'Finance, Compliance and Investment',
        },
        {
            id: 9,
            title: "Responsible AI",
            date: "July 18",
            time: "15:30 PM - 16:30 PM",
            type: "PANEL",
            description: "Redefining Finance: Precision, Speed, and Insight. This session will cover how AI is revolutionizing the financial sector.",
            day: 'SAT',
            category: 'Responsible AI',
        },
        {
            id: 10,
            title: "AI for Greater Good Challenge (Roadshow)",
            date: "July 18",
            time: "16:30 - 16:45 PM",
            type: "CHALLENGE",
            description: "Five teams from Columbia University, Carnegie Mellon University, Babson College and McGill University will present their AI and Sustainability projects to win the AI for Greater Good Grand Prize, Second Place Award, Human-Centered AI Design Award, and the Community Impact Award.",
            day: 'SAT',
            category: 'Challenge',
        },
        {
            id: 11,
            title: "AI for Greater Good Foundation",
            date: "July 18",
            time: "16:45 PM - 17:00 PM",
            type: "EVENT",
            description: "Introducing the AI for Greater Good Foundation, a foundation dedicated to applying artificial intelligence to solve humanity's most urgent challenges. We believe AI should be a force that enhances human well-being, promotes equity, and empowers communities around the world.",
            day: 'SAT',
            category: 'Foundation',
        }
    ]
};


